vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        recipe_images:
            uri_prefix: /images/recipe_images
            upload_destination: '%kernel.project_dir%/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
